---
version: '3'

services:
  db:
    image: mysql:5.7
    container_name: wellandgood-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wp
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wellandgood:1
    container_name: wellandgood-app
    ports:
      - "9000:9000"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
    volumes:
      - app-volume:/var/www/html
    networks:
      - app-network

  nginx:
    depends_on:
      - wordpress
    image: nginx-wellandgood:1
    container_name: wellandgood-nginx
    ports:
      - "80:80"
    volumes:
      - app-volume:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-volume: